// <auto-generated />
using System;
using BookATrip.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookATrip.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260226130213_AddTrips")]
    partial class AddTrips
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("BookATrip.Api.Data.Entities.TestTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestTables");
                });

            modelBuilder.Entity("BookATrip.Api.Models.Attraction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TripDayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TripDayId");

                    b.ToTable("Attraction");

                    b.HasData(
                        new
                        {
                            Id = "attr-1",
                            Category = "Food",
                            Description = "Vibrant open-air market with local food, spices, and street food.",
                            DurationInMinutes = 90,
                            Name = "Carmel Market",
                            TripDayId = 1
                        },
                        new
                        {
                            Id = "attr-2",
                            Category = "Museum",
                            Description = "World-class art museum featuring Israeli and international collections.",
                            DurationInMinutes = 120,
                            Name = "Tel Aviv Museum of Art",
                            TripDayId = 1
                        },
                        new
                        {
                            Id = "attr-3",
                            Category = "Nature",
                            Description = "Ancient port city with winding alleys, galleries, and sea views.",
                            DurationInMinutes = 180,
                            Name = "Jaffa Old City",
                            TripDayId = 2
                        });
                });

            modelBuilder.Entity("BookATrip.Api.Models.Trip", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Budget")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Food")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PointsOfInterest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TravelersCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = "trip-1",
                            Budget = "Medium",
                            Destination = "Tel Aviv, Israel",
                            EndDate = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Food = "Kosher",
                            Note = "First trip to Israel!",
                            Pace = "Medium",
                            PointsOfInterest = "[2,1,0]",
                            StartDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "3 Days in Tel Aviv",
                            Transport = "PublicTransport",
                            TravelersCount = 2
                        });
                });

            modelBuilder.Entity("BookATrip.Api.Models.TripDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TripDay");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayNumber = 1,
                            StartLocation = "Ben Gurion Airport",
                            TripId = "trip-1"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayNumber = 2,
                            StartLocation = "Hotel",
                            TripId = "trip-1"
                        });
                });

            modelBuilder.Entity("BookATrip.Api.Models.Attraction", b =>
                {
                    b.HasOne("BookATrip.Api.Models.TripDay", null)
                        .WithMany("Attractions")
                        .HasForeignKey("TripDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BookATrip.Api.Models.Location", "Location", b1 =>
                        {
                            b1.Property<string>("AttractionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Location_Address");

                            b1.Property<double>("Lat")
                                .HasColumnType("REAL")
                                .HasColumnName("Location_Lat");

                            b1.Property<double>("Lng")
                                .HasColumnType("REAL")
                                .HasColumnName("Location_Lng");

                            b1.HasKey("AttractionId");

                            b1.ToTable("Attraction");

                            b1.WithOwner()
                                .HasForeignKey("AttractionId");

                            b1.HasData(
                                new
                                {
                                    AttractionId = "attr-1",
                                    Address = "HaCarmel St, Tel Aviv",
                                    Lat = 32.065399999999997,
                                    Lng = 34.768799999999999
                                },
                                new
                                {
                                    AttractionId = "attr-2",
                                    Address = "27 Shaul HaMelech Blvd, Tel Aviv",
                                    Lat = 32.077300000000001,
                                    Lng = 34.786799999999999
                                },
                                new
                                {
                                    AttractionId = "attr-3",
                                    Address = "Old Jaffa, Tel Aviv",
                                    Lat = 32.051499999999997,
                                    Lng = 34.751300000000001
                                });
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("BookATrip.Api.Models.TripDay", b =>
                {
                    b.HasOne("BookATrip.Api.Models.Trip", null)
                        .WithMany("Days")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookATrip.Api.Models.Trip", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("BookATrip.Api.Models.TripDay", b =>
                {
                    b.Navigation("Attractions");
                });
#pragma warning restore 612, 618
        }
    }
}
